name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Run the program and build the result files.
    - name: Generate results for test cases
      run: sh ./scripts/testing_build.sh
    # Run tests on the results.
    - name: Test the results for test cases.
      run: sh ./scripts/testing_test.sh
      

        
